# Copyright © 2015-2019 Collabora Ltd.
#
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation files
# (the "Software"), to deal in the Software without restriction,
# including without limitation the rights to use, copy, modify, merge,
# publish, distribute, sublicense, and/or sell copies of the Software,
# and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
# BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
# ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

image: debian:buster-slim

stages:
  - build

before_script:
  - ./tools/ci-install.sh

variables:
  dbus_ci_configure_flags: ''
  ci_in_docker: "yes"
  ci_parallel: "2"
  ci_sudo: "yes"
  ci_distro: "debian"
  ci_suite: "buster"

build:python3.5:
  stage: build
  image: "debian:stretch-slim"
  variables:
    ci_suite: stretch
    dbus_ci_system_python: python3
  script: &script
    - chown -R user .
    - runuser -u user -- env PATH="/usr/lib/ccache:$PATH" ./tools/ci-build.sh $dbus_ci_configure_flags

build:python3.5-dbg:
  stage: build
  image: "debian:stretch-slim"
  variables:
    ci_suite: stretch
    dbus_ci_system_python: python3-dbg
  script: *script

build:python3.7:
  stage: build
  variables:
    dbus_ci_system_python: python3
  script: *script

build:python3.7-dbg:
  stage: build
  variables:
    dbus_ci_system_python: python3-dbg
  script: *script

build:python3.9:
  stage: build
  image: "debian:bullseye-slim"
  variables:
    ci_suite: bullseye
    dbus_ci_system_python: python3.9
  script: *script

build:python3.9-dbg:
  stage: build
  image: "debian:bullseye-slim"
  variables:
    ci_suite: bullseye
    dbus_ci_system_python: python3.9-dbg
    dbus_ci_system_python_module_suffix: -dbg
  script: *script

build:python3.10:
  stage: build
  image: "ubuntu:impish"
  variables:
    ci_distro: ubuntu
    ci_suite: impish
    dbus_ci_system_python: python3.10
    dbus_ci_configure_flags: --disable-documentation
    DISTCHECK_CONFIGURE_FLAGS: --disable-documentation
  script: *script

# vim:set sw=2 sts=2 et:
